export const FETCH_SYSTEM_MENU_BEGIN = 'FETCH_SYSTEM_MENU_BEGIN'
export const FETCH_SYSTEM_MENU_SUCCESS = 'FETCH_SYSTEM_MENU_SUCCESS'
export const FETCH_SYSTEM_MENU_FAILED = 'FETCH_SYSTEM_MENU_FAILED'

export const SET_SYSTEM_MENU_SEARCH_INPUT = 'SET_SYSTEM_MENU_SEARCH_INPUT'
export const CLEAR_SYSTEM_MENU_ADD_OR_EDIT_INPUT =
  'CLEAR_SYSTEM_MENU_ADD_OR_EDIT_INPUT'
export const SYSTEM_MENU_ADD_OR_EDIT_INPUT = 'SYSTEM_MENU_ADD_OR_EDIT_INPUT'

export const FETCH_SYSTEM_MENU_DETAIL_BEGIN = 'FETCH_SYSTEM_MENU_DETAIL_BEGIN'
export const FETCH_SYSTEM_MENU_DETAIL_SUCCESS =
  'FETCH_SYSTEM_MENU_DETAIL_SUCCESS'
export const FETCH_SYSTEM_MENU_DETAIL_FAILED = 'FETCH_SYSTEM_MENU_DETAIL_FAILED'
