export const FETCH_UPLOAD_FILE_URL_BEGIN = 'FETCH_UPLOAD_FILE_URL_BEGIN'
export const FETCH_UPLOAD_FILE_URL_SUCCESS = 'FETCH_UPLOAD_FILE_URL_SUCCESS'
export const FETCH_UPLOAD_FILE_URL_FAILED = 'FETCH_UPLOAD_FILE_URL_FAILED'
