export const GOODS_SPECS_MODAL_TRIGGER = 'GOODS_SPECS_MODAL_TRIGGER'

export const SET_GOODS_LIST_SEARCH_INPUT = 'SET_GOODS_LIST_SEARCH_INPUT'
export const FETCH_GOODS_LIST_BEGIN = 'FETCH_GOODS_LIST_BEGIN'
export const FETCH_GOODS_LIST_SUCCESS = 'FETCH_GOODS_LIST_SUCCESS'
export const FETCH_GOODS_LIST_FAILED = 'FETCH_GOODS_LIST_FAILED'

export const FETCH_GOODS_DETAIL_BEGIN = 'FETCH_GOODS_DETAIL_BEGIN'
export const FETCH_GOODS_DETAIL_SUCCESS = 'FETCH_GOODS_DETAIL_SUCCESS'
export const FETCH_GOODS_DETAIL_FAILED = 'FETCH_GOODS_DETAIL_FAILED'
export const CLEAR_GOODS_DETAIL = 'CLEAR_GOODS_DETAIL'
