export const FETCH_SYSTEM_RESOURCE_BEGIN = 'FETCH_SYSTEM_RESOURCE_BEGIN'
export const FETCH_SYSTEM_RESOURCE_SUCCESS = 'FETCH_SYSTEM_RESOURCE_SUCCESS'
export const FETCH_SYSTEM_RESOURCE_FAILED = 'FETCH_SYSTEM_RESOURCE_FAILED'

export const FETCH_SYSTEM_ROLE_RESOURCE_BEGIN =
  'FETCH_SYSTEM_ROLE_RESOURCE_BEGIN'
export const FETCH_SYSTEM_ROLE_RESOURCE_SUCCESS =
  'FETCH_SYSTEM_ROLE_RESOURCE_SUCCESS'
export const FETCH_SYSTEM_ROLE_RESOURCE_FAILED =
  'FETCH_SYSTEM_ROLE_RESOURCE_FAILED'

export const SUBMIT_SYSTEM_ROLE_RESOURCE_BEGIN =
  'SUBMIT_SYSTEM_ROLE_RESOURCE_BEGIN'
export const SUBMIT_SYSTEM_ROLE_RESOURCE_SUCCESS =
  'SUBMIT_SYSTEM_ROLE_RESOURCE_SUCCESS'
export const SUBMIT_SYSTEM_ROLE_RESOURCE_FAILED =
  'SUBMIT_SYSTEM_ROLE_RESOURCE_FAILED'

export const SET_SYSTEM_RESOURCE_SEARCH_INPUT =
  'SET_SYSTEM_RESOURCE_SEARCH_INPUT'
export const CLEAR_SYSTEM_RESOURCE_ADD_OR_EDIT_INPUT =
  'CLEAR_SYSTEM_RESOURCE_ADD_OR_EDIT_INPUT'
export const SYSTEM_RESOURCE_ADD_OR_EDIT_INPUT =
  'SYSTEM_RESOURCE_ADD_OR_EDIT_INPUT'

export const FETCH_SYSTEM_RESOURCE_DETAIL_BEGIN =
  'FETCH_SYSTEM_RESOURCE_DETAIL_BEGIN'
export const FETCH_SYSTEM_RESOURCE_DETAIL_SUCCESS =
  'FETCH_SYSTEM_RESOURCE_DETAIL_SUCCESS'
export const FETCH_SYSTEM_RESOURCE_DETAIL_FAILED =
  'FETCH_SYSTEM_RESOURCE_DETAIL_FAILED'
