export const FETCH_SIGNIN_BEGIN = 'FETCH_SIGNIN_BEGIN'
export const FETCH_SIGNIN_SUCCESS = 'FETCH_SIGNIN_SUCCESS'
export const FETCH_SIGNIN_FAILED = 'FETCH_SIGNIN_FAILED'

export const FETCH_USER_IFNO_BEGIN = 'FETCH_USER_IFNO_BEGIN'
export const FETCH_USER_IFNO_SUCCESS = 'FETCH_USER_IFNO_SUCCESS'
export const FETCH_USER_IFNO_FAILED = 'FETCH_USER_IFNO_FAILED'
