export const SET_SYSTEM_ROLE_INPUT = 'SET_SYSTEM_ROLE_INPUT'

export const FETCH_SYSTEM_ROLE_BEGIN = 'FETCH_SYSTEM_ROLE_BEGIN'
export const FETCH_SYSTEM_ROLE_SUCCESS = 'FETCH_SYSTEM_ROLE_SUCCESS'
export const FETCH_SYSTEM_ROLE_FAILED = 'FETCH_SYSTEM_ROLE_FAILED'

export const CLEAR_SYSTEM_ROLE_ADD_OR_EDIT_INPUT =
  'CLEAR_SYSTEM_ROLE_ADD_OR_EDIT_INPUT'
export const SET_SYSTEM_ROLE_ADD_OR_EDIT_INPUT =
  'SET_SYSTEM_ROLE_ADD_OR_EDIT_INPUT'

export const FETCH_SYSTEM_ROLE_DETAIL_BEGIN = 'FETCH_SYSTEM_ROLE_DETAIL_BEGIN'
export const FETCH_SYSTEM_ROLE_DETAIL_SUCCESS =
  'FETCH_SYSTEM_ROLE_DETAIL_SUCCESS'
export const FETCH_SYSTEM_ROLE_DETAIL_FAILED = 'FETCH_SYSTEM_ROLE_DETAIL_FAILED'

export const FETCH_ROLE_MENU_BEGIN = 'FETCH_ROLE_MENU_BEGIN'
export const FETCH_ROLE_MENU_SUCCESS = 'FETCH_ROLE_MENU_SUCCESS'
export const FETCH_ROLE_MENU_FAILED = 'FETCH_ROLE_MENU_FAILED'

export const SET_ROLE_MENU_IDS = 'SET_ROLE_MENU_IDS'
